### PR TITLE
Update datasketches-memory 2.0.0

### PR DESCRIPTION
**Pull request by davecromberge**
Uses new datasketches memory 2.0.0 which has added support for Java9 - 13.

### CODE REVIEW

**Comment by leerho** [comment]
"Coveralls API failed with HTTP status 405: Not Allowed (Response doesn't contain Content-Type header)"

Hmm. What is this about?  I haven't seen this one before.

**Comment by leerho** [comment]
Retried running the tests. Still fails.

**Comment by leerho** [comment]
Coveralls is down for maintenance.  Perhaps that is the problem.

**Comment by davecromberge** [comment]
In addition to the coveralls failure - I've noticed that the matrix tests have been failing intermittently lately both here and in datasketches-memory.  The issue seems to be related to an aggressive timeout setting on downloading the super pom.  I'd like to investigate extending the timeout setting in the GH actions to make the tests more reliable.

**Comment by leerho** [comment]
Coveralls site is back up, but this job still fails with error 405 (Not allowed).

**Comment by davecromberge** [comment]
@leerho the checks have now passed successfully - I think that the issues were related to the coveralls maintenance.  

As for the other transient issue that I mentioned with the super pom, I will have to keep an eye out for any failures and potentially increase HTTP timeouts via maven arguments.  My preference is to monitor the situation instead of adding complexity to the GH actions build.

**Comment by leerho** [comment]
Agreed.

**Pull request merged**
